LibrIT/passhport

- app/models_mod/target/__init__.py
- app/models_mod/targetgroup/__init__.py
- app/models_mod/user/__init__.py
- app/models_mod/usergroup/__init__.py
- app/views_mod/target/__init__.py
- app/views_mod/targetgroup/__init__.py
- app/views_mod/user/__init__.py
- app/views_mod/usergroup/__init__.py
- install.sh
- test_curl.txt
Installation script only hceck requierements at the moment.
No more """ are used for strings, only simple ".
The syntax "this is %s text" % ("obsolete") will be deprecated one day or another, so moved on to the usage of format()
> Resolving issue #25, some formatting and initiate installation script

- install.sh
Bringing some enhancement to the install script
> Bringing some enhancements.

- install.sh
- passhportd/config.py
- passhportd/db_create.py
install.sh script now copies scripts files into passhport_user_dir, and database is created into passhport_user_dir/var/. .
Corrected typo in install.sh script (Issue #76).
> Installation enhancement (use passhport user as base dir)

- passhport_admin/tests/passhport_cli_tests_target.sh
- passhportd/app/models_mod/target/__init__.py
- passhportd/app/models_mod/targetgroup/__init__.py
- passhportd/app/models_mod/usergroup/__init__.py
> Broken for the fun

- passhportd/app/models_mod/target/__init__.py
- passhportd/app/models_mod/targetgroup/__init__.py
> Nicer syntax of last commit

- passhport/passhport
- passhportd/app/views_mod/user/__init__.py
- scripts_utils/passhport-admin_v0.sh
> Corrections on user deletion #130

- scripts_utils/launch_passhportd_docker_v0.sh
Created a small script, that is aimed to be launched by docker, to start the passhportd daemon.
> Docker launch script

- passhportd/app/views_mod/targetgroup/api.py
- passhportd/app/views_mod/usergroup/api.py
Made some minor changes on user list API.
> Added the API url/managment for usergroup list and targetgroup list.

- scripts_utils/openssl-for-passhportd.cnf
- scripts_utils/passhport-install-script-debian-8-9.sh
Corrected a typo in install script
> Added some DNS on the certificate

- passhport/passhport
#209
I only added a try/except block.
> display useful message when no user exists in db

- tools/openssl-for-passhportd.cnf
- tools/passhport-install-script-debian-8-9.sh
- tools/passhportd.service
Added systemd service support
Removed IP entry from DNS altname in SSL template
> Added systemd service support

- docs/installation-and-configuration/index.rst
- docs/installation-and-configuration/installation-on-centos.rst
- docs/installation-and-configuration/installation-on-debian.rst
Chapter correction (there was a ToC issue)
Corrected the CentOS documentation concerning the EPEL installation
Removed apt reference in CentOS documentation
> Documentation update

- docs/installation-and-configuration/add-bash_completion-to-passhport-admin.rst
- docs/installation-and-configuration/index.rst
- docs/installation-and-configuration/use-postgresql-as-backend.rst
- docs/po/fr/LC_MESSAGES/installation-and-configuration/add-bash_completion-to-passhport-admin.po
- docs/po/fr/LC_MESSAGES/installation-and-configuration/index.po
- docs/po/fr/LC_MESSAGES/installation-and-configuration/installation-on-centos.po
- docs/po/fr/LC_MESSAGES/installation-and-configuration/installation-on-debian.po
- docs/po/fr/LC_MESSAGES/installation-and-configuration/use-postgresql-as-backend.po
- tools/passhport-admin.bash_completion
- tools/passhport-install-script-centos7.sh
- tools/passhport-install-script-debian-8-9.sh
Added a bash_completion file (tools/passhport-admin.bash_completion)
Changed the passhport-install-* scripts to automatically install the file
Added a section into the documentation
> bash_completion capability for passhport-admin

- docs/passhport-admin/target.rst
- docs/passhport-admin/user.rst
- docs/po/fr/LC_MESSAGES/passhport-admin/target.po
- docs/po/fr/LC_MESSAGES/passhport-admin/targetgroup.po
- docs/po/fr/LC_MESSAGES/passhport-admin/user.po
- docs/po/fr/LC_MESSAGES/passhport-admin/usergroup.po
Doc: Typos
Doc: Add the user section in the passhport-admin chapter
Doc: User section translation in FR.
Doc: Add empty tranlation file…
Doc: typo in translation of target section in passhport-admin chapter
> Doc update

- tools/passhport-install-script-centos7.sh
- tools/passhport-install-script-debian-8-9.sh
Doc: Typos
Doc: Add the user section in the passhport-admin chapter
Doc: User section translation in FR.
Doc: Add empty tranlation file…
Doc: typo in translation of target section in passhport-admin chapter
> Installation script enhancement for issue #192

- tools/passhport-install-script-centos7.sh
Added some dependencies pulling on CentOS, in order to be able to build
psutil pip module (gcc and python34-devel)
> Install script : psutil for CentOS

- passhport/passhport
From now, if you chose a determined target name, this one will be selected. If a target has the this name as hostname, it will be choose only if you can access that only.
> Change server selection behavior

- passhport/connections_utils/scp.py
- passhport/passhport
- passhport/passhport.ini
Syntax: 
scp passhport@bastion:targetname//distantusername//distantserver//path/on/distantserver/file ~/local/path
> Add possibility to scp on distant server via a target in one command

- passhportd/app/models_mod/targetgroup.py
- passhportd/app/models_mod/user.py
- passhportd/app/models_mod/usergroup.py
Bad formating of the json due to comma.
> fix(models_mod/user.py): Fix simplejson def

- passhportd/app/views.py
In case of multiple connections on a row by the same user, the daily report quickly becomes hard to read. The goal of this PR is to implement a function which will reduce consecutive entries of the daily list for a given user to a single entry.
> the daily report list is now reduced for a given user

- passhportd/app/views.py
A bug was found in the reduce_daily_list function.
> refactored the reduce_daily_list function
